### ISSUE TITLE
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: 'XX.XX.XX.XXX\r'

### ISSUE THREAD

**Issue by drkbllo** [arthaud/git-dumper#29]
STARTING TO DUMP MOTHERFUCKER
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\6\git-dumper.py", line 736, in <module>
    main()
  File "C:\Users\Administrator\Desktop\6\git-dumper.py", line 715, in main
    os.makedirs(args.directory)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\os.py", line 225, in makedirs
    mkdir(name, mode)

OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: '13.52.145.243\r'OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: 'XX.XX.XX.XXX\r'

**Comment by arthaud** [comment]
Sorry, we don't support windows. Try using WSL.
