### ISSUE TITLE
AttributeError: 'Index' object has no attribute 'iterblobs'

### ISSUE THREAD

**Issue by thistehneisen** [arthaud/git-dumper#32]
```
[-] Finding packs
[-] Finding objects
Traceback (most recent call last):
  File "/usr/local/bin/git-dumper", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/git_dumper.py", line 724, in main
    fetch_git(
  File "/usr/local/lib/python3.8/dist-packages/git_dumper.py", line 583, in fetch_git
    for entry in index.iterblobs():
AttributeError: 'Index' object has no attribute 'iterblobs'
```

**Comment by battlemonger** [comment]
line 583 in git-dumper.py, change deprecated iterblobs to iterobjects.
