### ISSUE TITLE
Git dumper doesnt work on mac m1

### ISSUE THREAD

**Issue by AzhariRamadhan** [arthaud/git-dumper#35]
this error

Traceback (most recent call last):
  File "/Users/azhariramadhan/Documents/pentest-tools/git-dumper/./git_dumper.py", line 20, in <module>
    import socks
  File "/opt/homebrew/lib/python3.10/site-packages/socks.py", line 58, in <module>
    from collections import Callable
ImportError: cannot import name 'Callable' from 'collections' (/opt/homebrew/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/collections/__init__.py)

**Comment by za** [comment]
Hi @AzhariRamadhan 

How did you install it? Did you create a new virtual environment before installing the requirements?
